# @package _global_

experiment:
  output_dir: benchmark/
  texts: 
    - gerrig
    - delatorre
    - lehne
    - brewer
  augs:
    - distraction_insertion
    - swap_words
    - shuffle_sentences
    - introduce_typos
    - word_swap_embedding
    - change_character_names
    - context_removal
    - word_swap_homoglyph
    - sentence_paraphrase
    - backtranslation
    - synonym_replacement
    - caesar_cipher
    - none
