api:
  key: "YOUR_TOGETHER_API_KEY"

model:
  name: "gpt-3.5-turbo"
  max_tokens: 150
  temperature: 0.7
  top_k: 50
  top_p: 0.95
  repetition_penalty: 1.0

experiment:
  story_file: "stories/casino_royale.txt"
  output_dir: "outputs/gerrig_experiment_1"
