"""
Define experiments from Lehne, M. and Koelsch, S. 2015. Toward a general psychological model of tension and suspense. Frontiers in psychology. 6, (Feb. 2015). DOI:https://doi.org/10.3389/fpsyg.2015.00079.
"""

common_prompt_template = """The following is E. T. A. Hoffmann's "The Sandman". 

After each paragraph, rate how suspensful you found it to be on a 10-point scale, where 1 is "not suspensful" and 10 is "very suspensful".
"""


experiment_text = """
1 Nathanael to Lothar: Surely you are all full of unrest that I haven't written for so long. Mother is probably angry, and Klara may think that I have completely forgotten my lovely angel image. – But that is not the case; I remember you all daily and hourly. – Oh, how I was able to write to you in the torn mood of my mind that had previously disturbed all my thoughts! – Something terrible has come into my life! Dark premonitions of a terrible fate threatening me spread over me like black cloud shadows.

2 Now let me tell you what happened to me. In short, the terrible thing that happened to me was nothing other than that a few days ago a barometer dealer came into my room and offered me his goods. I didn't buy anything and threatened to throw him down the stairs, but he walked away on his own. You suspect that only my own relationships that have a deep impact on my life can give this incident meaning. That's how it is indeed. With all my strength, I will pull myself together to calmly and patiently tell you so much about my early youth that everything will appear clearly and vividly in bright images to your active mind. - Now let's get down to business!

3 Apart from lunch, we, my brothers and sisters, saw little of our father during the day. He was probably very busy with his work. After dinner we all went into our father's study and sat around a round table. Father often told us many wonderful stories and became so enthusiastic about them that his pipe kept going out, which I had to light again by holding out burning paper to him, which was a great amusement for me. But he often gave us picture books, sat silent and rigid in his armchair and blew out thick clouds of steam. On such evenings mother was very sad, and as soon as the clock struck nine she said: "Now, children! - to bed! The Sandman is coming, I can tell." And every time I did hear heavy footsteps clattering up the stairs.

4 Full of curiosity to find out more about this Sandman, I finally asked the old woman who looked after my youngest sister what kind of man the Sandman was. "Oh, Thanelchen," she replied, "don't you know? He's a wicked man who comes to the children when they don't want to go to bed and throws handfuls of sand in their eyes so that they jump out of their heads bloody. He then throws them in a sack and carries them to the half-moon to feed his children. They sit there in the nest and have crooked beaks with which they peck out the eyes of naughty human children." The image of the cruel Sandman now formed a horrible picture in my mind; as soon as he thundered up the stairs in the evening, I trembled with fear and horror. All my mother could get out of me was the cry, stammered through tears: "The Sandman! The Sandman!" The horrible apparition of the Sandman tormented me all night long.

5 I had already grown old enough to realize that what the nurse had told me about the Sandman and his children's nest in the half-moon could not be entirely true; nevertheless, the Sandman remained a horrible ghost to me, and I was filled with horror - terror when I heard him not only coming up the stairs, but also violently throwing open my father's door and entering. His company with my father began to occupy my imagination more and more: an insurmountable shyness prevented me from asking my father about it, but the desire to discover the secret myself, to see the fabulous Sandman, grew in me more and more as the years went by.

6 From my father's silence and my mother's sadness, I realized one evening that the Sandman was coming; I therefore feigned great tiredness, left the room before nine o'clock and hid in a hiding place close to the door. The front door creaked, and I walked through the hall to the stairs with slow, heavy, thundering steps. I quietly opened my father's door to the living room.

7 He was sitting, as usual, silent and rigid, with his back turned to the door. He didn't notice me. I was quickly inside and behind the curtain. Closer - ever closer the footsteps rumbled - there was a strange coughing and scraping and humming outside. My heart trembled with fear and expectation. Right in front of the door there was a sharp kick - a violent blow on the handle, the door burst open with a rattle! - Forcing myself to pull myself together, I cautiously looked out.

8 The Sandman is standing in the middle of the room in front of my father! The terrible Sandman is the old lawyer Coppelius, who sometimes eats lunch with us! But the most hideous figure could not have aroused more horror in me than this Coppelius. - Imagine a tall, broad-shouldered man with a misshapen, thick head, bushy gray eyebrows, from beneath which a pair of greenish cat's eyes sparkled piercingly. The crooked mouth often twists into a malicious laugh. The whole figure was generally hideous; but above all we children disliked his large, knotted, hairy fists, so that we no longer liked what he touched with them. He had noticed this, and now it was his pleasure to touch a piece of cake or a sweet fruit under one pretext or another, so that we, with bright tears in our eyes, no longer wanted to enjoy the treat out of disgust and revulsion.

9 I was under a spell. At the risk of being discovered and severely punished, I stood there, my head sticking out from behind the curtains, listening. My father received Coppelius solemnly. "Up! - to work," he called in a hoarse voice and threw off his coat. The father quietly and grimly took off his dressing gown, and both dressed in long black smocks. The father opened the double doors of a closet; but I saw that what I had thought was a cupboard for so long was not a cupboard, but rather a black cavity in which stood a small stove. Coppelius came over, and a blue flame crackled on the stove.

10 Oh God! - when my old father now bent down to the fire, he looked quite different. A horrible, convulsive pain seemed to have twisted his gentle, honest features into an ugly devilish image. He looked like Coppelius. The latter swung the glowing red tongs and used them to pull brightly shining masses out of the thick smoke. It seemed to me as if human faces were becoming visible all around, but without eyes - hideous, deep black caves instead. "Eyes, eyes!" cried Coppelius in a dull, booming voice. I screamed, seized by wild terror, and rushed out of my hiding place. Then Coppelius grabbed me. "Little beast! – little beast!” he bleated, baring his teeth, and threw me onto the stove so that the flames began to singe my hair: “Now we have eyes – a beautiful pair of children’s eyes.” So whispered Coppelius, and with his fists he grabbed glowing red grains from the flames, which he wanted to sprinkle in my eyes.

11 Then my father raised his hands imploringly and called out: "Master! Master! Leave my Nathanael his eyes - leave them to him!" Coppelius laughed shrilly and called out: "The boy can keep his eyes and cry his share in the world; but now we will examine the mechanism of the hands and feet properly." And with that he grabbed me so hard that the joints cracked, and unscrewed my hands and feet and put them back in now here, now there. "It's not right anywhere! It's fine the way it was! - The old man has understood it!" So hissed and lisped Coppelius; but everything around me turned black and dark, a sudden cramp shot through nerve and bone - I felt nothing anymore.

12 Why should I tire you, my dear Lothar! Why should I tell you in such detail when there is still so much left to say? Enough! – I had been discovered eavesdropping and had been mistreated by Coppelius. Fear and terror had given me a fever, which kept me ill for several weeks. “Is the Sandman still here?” – That was my first healthy word and the sign of my recovery. – I can only tell you about the most terrible moment of my youth; then you will be convinced that a dark fate really has hung a gloomy veil of clouds over my life, which I may only tear apart when I die.

13 Coppelius was no longer seen; it was said that he had left town. A year may have passed when we sat at the round table in the evening according to the old custom. Then we suddenly heard the front door creak on its hinges and slow, heavy footsteps rumbled up the stairs. “That’s Coppelius,” said my mother, turning pale. “Yes! – it’s Coppelius,” repeated my father in a weak, broken voice. Tears poured from my mother’s eyes. "But father, father!" she cried, "must it be like this?" - "For the last time!" he replied, "for the last time he's coming to me, I promise you. Just go, go with the children! - Go to bed! Good night!"

14 I felt as if I were pressed into heavy, cold stone - my breath caught! - My mother grabbed me by the arm: "Come, Nathanael, just come!" - I let myself be led away, I went into my room. "Be quiet, be quiet, lie down in bed! - Sleep - sleep," my mother called after me; but tormented by indescribable inner fear and unrest, I could not close my eyes. It was probably already midnight when a terrible blow occurred. "That's Coppelius!" I cried in horror and jumped out of bed. Then there was a shriek of piercing, hopeless misery. I rushed to my father's room. The door was open, suffocating steam billowed out towards me. The maid cried out: "Ah, the Lord! - the Lord!"

15 My father lay dead on the floor in front of the steaming stove, his face burned black and horribly distorted. Around him, his sisters howled and whimpered - his mother was unconscious beside him! - "Coppelius, wicked Satan, you have killed your father!" - I screamed; I lost my senses. When my father was laid in the coffin two days later, his features had returned to their mild and gentle state, as they had been in life. The explosion had awakened the neighbors, the incident was reported and brought to the attention of the authorities, who wanted to summon Coppelius to account. But he had disappeared from the scene without a trace.

16 If I now tell you, my dear friend, that the barometer dealer was the wicked Coppelius, you will not hold it against me that I interpret the hostile apparition as bringing great disaster. He was dressed differently, but Coppelius' figure and facial features are too deeply engraved in my mind for there to be any mistake here. Moreover, Coppelius has not even changed his name. He claims to be a Piedmontese mechanic and calls himself Giuseppe Coppola. I am determined to take him on and avenge my father's death. Don't tell your mother about the appearance of the horrible monster - send my greetings to my dear, faithful Clara. Farewell, etc., etc.

17 Clara to Nathanael: It is true that you have not written to me for quite a long time, but I still believe that you have me in your mind and thoughts. For you must have thought of me very vividly when you wanted to send your last letter to Brother Lothar and addressed it to me instead of to him. I opened the letter with joy and only realized my mistake when I read the words: "Ah, my dearest Lothar!" - Now I should not have read on, but given the letter to my brother. The beginning of your letter shocked me deeply. - Ah, my dearest Nathanael! What could have happened in your life that was so terrible?

18 I read and read! - Your description of the disgusting Coppelius is horrible. Only now did I hear how your good old father died such a terrible death. Brother Lothar, to whom I delivered his property, tried to calm me down, but he was unsuccessful. The fatal barometer dealer Giuseppe Coppola followed me everywhere. But soon, the very next day, everything had changed in me. Don't be angry with me, my dearest love, that despite your strange suspicion that Coppelius will do something bad to you, I am completely cheerful and unprejudiced, as always.

19 I will just confess to you straight out that, in my opinion, all the horrible and terrible things you speak of were only going on inside you. Old Coppelius may have been repulsive enough, but the fact that he hated children made you children really loathe him. Of course, in your childish mind, the terrible Sandman from the fairy tale was now associated with old Coppelius. The sinister goings-on with your father at night were probably nothing other than the two of them secretly conducting alchemical experiments. Your father certainly brought about his death through his own carelessness, and Coppelius is not to blame for it.

20 I beg you, put the ugly lawyer Coppelius and the barometer man Giuseppe Coppola completely out of your mind. Be assured that these strange figures have no power over you; only the belief in their hostile power can actually make them hostile to you. I have resolved to appear before you as your guardian spirit and to banish the ugly Coppola with loud laughter, should he perhaps think of bothering you in your dreams. Forever, my most dearly beloved Nathanael etc. etc. etc.

21 Nathanael to Lothar: I am very displeased that Klara recently opened and read the letter to you by mistake. She wrote me a very profound philosophical letter in which she proves in detail that Coppelius and Coppola only exist in my inner being. In fact, one would not believe that the mind that often shines out of such bright, faithfully smiling child's eyes like a lovely, sweet dream could discuss things so intelligently, so masterfully. She is referring to you. You read her logical lectures so that she can sift through everything carefully and learn to separate things. - Stop that!

22 Incidentally, it is quite certain that the barometer seller Giuseppe Coppola is by no means the old lawyer Coppelius. I am attending lectures by the recently arrived professor of physics, whose name is Spallanzani and who is of Italian descent. He has known Coppola for many years, and you can also tell from his accent that he really is from Piedmont. Coppelius was a German. I am not entirely reassured. You and Klara may think I am a gloomy dreamer, but I cannot shake the impression that Coppelius's accursed face makes on me. I am glad that he is out of town, as Spallanzani tells me.

23 - Recently I climbed the stairs and noticed that the curtain that is usually drawn tightly across a glass door had a small gap at the side. I do not know how I came to look through it curiously. A tall, very slim, perfectly symmetrical, beautifully dressed woman was sitting in the room in front of a small table on which she had placed both arms, her hands folded together. She was sitting opposite the door, so that I could see her angelic face in full. She did not seem to notice me, and her eyes were fixed, I would almost say she had no vision, it seemed to me as if she were sleeping with her eyes open. I felt quite uneasy, so I crept quietly away into the auditorium next door.

24 I later learned that the figure I had seen was Spallanzani's daughter Olimpia, whom he has locked up in a strange and bad way, so that no one is allowed to go near her. - In the end, there is something wrong with her, she may be stupid or something else. - But why am I writing all this to you? I could have told you better and in more detail in person. Know that I will be with you for over a fortnight. I must see my sweet, dear angel, my Klara, again. Then the bad mood that was trying to take hold of me will be gone. A thousand greetings, etc., etc.

25 Nothing can be invented more strange and wonderful than what happened to my poor friend, the young student Nathanael, and what I have undertaken to tell you, dear reader! In order to make clearer what needs to be known at the beginning, it should be added to those letters that soon after Nathanael's father died, Clara and Lothar, children of a distant relative who had also died and left them orphaned, were taken into the house by Nathanael's mother. Clara and Nathanael developed a strong affection for each other; they were therefore engaged when Nathanael left the place to continue his studies in G. There he is now, attending lectures by the famous professor of physics, Spallanzani.

26 Now I could confidently continue with the story; but at this moment the image of Clara is so vivid before my eyes that I cannot look away. The mistaker and the hoverer played a nasty trick on her; for without saying too much, which was not in Clara's taciturn nature, her bright gaze and that subtle ironic smile said to them: Dear friends! How can you expect me to regard your fleeting shadows as real figures? For this reason, Clara was scolded by many as being cold, unfeeling, and prosaic; but others loved the intelligent girl immensely, but none more than Nathanael. Clara was attached to her lover with all her heart. With what delight she flew into his arms when he now, as he had promised in his last letter to Lothar, actually entered her mother's room in his hometown. It happened just as Nathanael had believed; When he saw Clara again, he thought neither of the lawyer Coppelius nor of Clara's sensible letter; all his resentment had disappeared.

27 But Nathanael was right when he wrote to his friend Lothar that the repulsive figure of Coppola had entered his life in a very hostile way. Everyone felt this, because Nathanael's whole being had changed completely in the first few days. He always spoke of how every person, believing themselves to be free, only serves as a cruel game for dark powers. He used to have a particular strength in charming, lively stories, which he wrote down and which Clara listened to with the deepest pleasure; now his poems were dark, incomprehensible, shapeless, so that, even if Clara did not say it out of consideration, he certainly felt how little they appealed to her. His annoyance with Clara's cold, prosaic nature grew stronger, Clara could not overcome her displeasure with Nathanael's dark, gloomy, boring mysticism, and so both of them grew further and further apart.

28 The figure of the ugly Coppelius had, as Nathanael had to admit, paled in his imagination, and it often cost him effort to paint him quite vividly in his poems. Finally it occurred to him to make the dark premonition that Coppelius would spoil his happiness in love the subject of a poem. He depicted himself and Clara, united in faithful love, but now and then it was as if a black fist reached into their lives and tore away some joy. Finally, when they were already standing at the altar, the terrible Coppelius appeared and touched Clara's lovely eyes; they leap into Nathanael's chest like bloody sparks, Coppelius grabs him and throws him into a flaming circle of fire that spins and carries him away with a roar. But through this wild roar he hears Clara's voice: "Can't you see me? Coppelius has deceived you, those weren't my eyes - I have my eyes, just look at me!" Nathanael looks into Clara's eyes; but it is Death who looks at him kindly with Clara's eyes.

29 While Nathanael was writing this, he was very calm and collected. But when he finally finished and read the poem out loud, he was seized with horror and cried out: "Whose horrible voice is that?" Soon, however, the whole thing seemed to him to be just a very successful poem, and it seemed to him as if it would ignite Clara's cold mind.

30 They, Nathanael and Clara, were sitting in their mother's little garden. Clara was very cheerful because Nathanael had not tormented her with his dreams and premonitions for the three days in which he had been writing that poem. Nathanael too spoke animatedly and happily of funny things as usual, so that Clara said: "Now I have you completely back. Do you see how we have driven away the ugly Coppelius?" Then Nathanael remembered that he had the poem in his pocket that he had wanted to read aloud. He immediately pulled out the pages and began to read. Clara, suspecting something boring as usual and resigning herself to it, began to knit quietly.

31 But as the gloomy clouds rose blacker and blacker, she let the knitted stocking fall and stared straight into Nathanael's eyes. He was irresistibly drawn away by his poetry, his inner fire colored his cheeks bright red, tears welled up from his eyes. - Finally he had closed his eyes, he groaned in deep exhaustion: "Ah! - Klara - Klara!" - Klara pressed him gently to her breast and said quietly but very seriously: "Nathanael - my dear Nathanael! - throw the crazy - nonsensical - insane fairy tale into the fire." Then Nathanael jumped up indignantly and shouted, pushing Klara away: "You lifeless, damned automaton!" He ran away, the deeply hurt Klara shed bitter tears: "Ah, he never loved me, because he doesn't understand me," she sobbed loudly.

32 Lothar went into the arbor; Klara had to tell him what had happened; every word of her accusation fell like a spark into his heart, so that the resentment he had long harbored against the dreamy Nathanael flared up into wild anger. He ran to Nathanael and reproached him for his senseless behavior towards his beloved sister in harsh words, which the quick-tempered Nathanael responded in kind. A duel was inevitable. They decided to fight behind the garden the following morning with sharp rapiers.

33 Klara had heard the fierce argument and seen that the fencing master brought the swords at dusk. She suspected what was about to happen. When they arrived at the battlefield, Lothar and Nathanael had just thrown off their coats in gloomy silence; with bloodthirsty fighting spirit in their burning eyes, they were about to attack each other when Klara rushed through the garden gate. Sobbing, she cried out loudly: "You wild, horrible people! - just knock me down now before you attack each other; for how can I live any longer in this world if the beloved has murdered the brother or the brother the beloved!"

34 Lothar lowered his weapon and looked down at the ground in silence, but in Nathanael's heart all the love he had ever felt for the lovely Clara was rekindled in heart-rending melancholy. The murder weapon fell from his hand and he fell at Clara's feet. "Can you ever forgive me, my only, dearly beloved Clara! - Can you forgive me, my dearly beloved brother Lothar!" - Lothar was moved by his friend's deep pain; with a thousand tears the three reconciled people embraced each other and swore not to leave each other in constant love and loyalty.

35 Nathanael felt as if a heavy burden had been lifted from him. He spent three more blissful days with his loved ones, then he returned to G., where he planned to stay for another year, but then return to his hometown forever. Nathanael was astonished when he went to his apartment and saw that the whole house had burned down. Although the fire had broken out in the laboratory of the pharmacist who lived on the lower floor, and the house had therefore burned from the bottom up, the bold, robust friends had managed to get into Nathanael's room on the upper floor in time and save books, manuscripts and instruments. They had carried everything unharmed to another house and taken over a room there, which Nathanael immediately moved into.

36 He paid no particular attention to the fact that he lived opposite Professor Spallanzani, and it seemed no more unusual to him when he noticed that from his window he could see straight into the room where Olimpia often sat alone, so that he could see her figure clearly, although her features remained indistinct and confused. He did notice that Olimpia often sat for hours at a small table in the same position, doing nothing, and that she was obviously staring at him with an unblinking gaze; he had to admit to himself that he had never seen a more beautiful figure; however, Clara in his heart, the stiff, rigid Olimpia remained utterly indifferent to him.

37 He was just writing to Klara when there was a soft knock on the door; it opened at his call, and Coppola's repulsive face looked in. Nathanael felt a trembling inside; remembering what Spallanzani had said to him about his countryman Coppola, and what he had so solemnly promised his beloved about Coppelius the Sandman, he was ashamed of his childish fear of ghosts, pulled himself together with all his might, and said as gently and calmly as possible: "I'm not buying a barometer, my dear friend! Just go!" But Coppola stepped into the room and said in a hoarse tone: "Oh, no barometer! - I've got a nice eye too - a nice eye!" Nathanael cried out in horror: "You madman, how can you have eyes? – Eyes – eyes?”

38 But at that moment Coppola had put his barometer aside, reached into his wide coat pockets and pulled out glasses, which he laid on the table. – “Now – now – glasses – glasses on your nose, put them on my eyes, those are my eyes – beautiful eyes!” – And with that he pulled out more and more glasses, so that the whole table began to flicker and sparkle strangely. A thousand eyes looked and twitched convulsively and stared up at Nathanael; but he could not look away from the table, and fiery glances jumped more and more wildly and shot their blood-red rays into Nathanael’s chest. Overcome by mad terror, he cried out: – “Stop, you horrible man!” – He had grabbed Coppola firmly by the arm, who was just reaching into his pocket to pull out more glasses.

39 Coppola gently freed himself with a hoarse laugh and with the words: “Ah! - nothing for you - but here are some nice glasses" - he had put all his glasses away and taken a number of large and small perspective glasses out of the side pocket of his coat. As soon as the glasses were gone, Nathanael became very calm and, thinking of Klara, he realized that the horrible ghost could only have come from within him and that Coppola could be a very honest mechanic and optician and by no means Coppelius's accursed double. To make up for everything, Nathanael decided to buy something from Coppola.

40 He picked up a small, very neatly made pocket perspective glass and looked through the window to examine it. Never in his life had he seen a glass that brought objects so cleanly, sharply and clearly close to his eyes. Involuntarily he looked into Spallanzani's room; Olimpia was sitting, as usual, in front of the small table. - Now Nathanael saw Olimpia's beautifully formed face for the first time. Only the eyes seemed strangely rigid and dead. But as he looked ever more closely through the glass, it was as if moist moonlight appeared in Olimpia's eyes. Nathanael lay in the window as if by magic, always looking at the heavenly-beautiful Olimpia.

41 A clearing of the throat and scratching woke him as if from a deep dream. Coppola was standing behind him: "Tre Zechini - three ducats." - Nathanael had completely forgotten about the optician, and quickly paid what was asked. "Adieu, dear friend!" - Coppola left the room, not without many strange sidelong glances at Nathanael. He heard him laughing loudly on the stairs. "Well," said Nathanael, "he's laughing at me because I've certainly paid him far too much for the little perspective!" - As he spoke these words quietly, it was as if a deep sigh of death echoed horribly through the room, Nathanael's breath caught in inner fear.

42 But he had sighed like that himself, he noticed that. "Klara," he said to himself, "is probably right to think I'm a tasteless ghost-seer." - Now he sat down to finish the letter to Klara, but a glance through the window convinced him that Olimpia was still sitting there, and in an instant, as if driven by an irresistible force, he jumped up, grabbed Coppola's perspective and could not tear himself away from Olimpia's seductive sight until his friend and brother Siegmund called him away to the lecture given by Professor Spallanzani.

43 When he was about to return to his apartment, he noticed a noisy commotion in Spallanzani's house. The doors were open, all kinds of equipment was being brought in, busy maids were sweeping, and inside carpenters and upholsterers were knocking and hammering. Nathanael stopped in the street in complete amazement; then Siegmund came up to him laughing and said: "Well, what do you say about our old Spallanzani?" Nathanael assured him that he could not say anything, since he knew absolutely nothing about the professor; then he learned from Siegmund that Spallanzani wanted to give a big party the next day, a concert and a ball, and that half the university was invited. It was widely known that Spallanzani was going to have his daughter Olimpia appear for the first time.

44 Nathanael found an invitation card and went to the professor at the appointed hour with his heart pounding. The company was large and brilliant. Olimpia appeared very richly and tastefully dressed. One had to admire her beautifully formed face and her stature. The somewhat oddly bent back and the wasp-like thinness of her body seemed to have been caused by too much constriction. There was something measured and stiff about her step and posture that struck some as unpleasant; they attributed this to the constraints imposed on her by the company.

45 The concert began. Olimpia played the piano with great skill and also performed a bravura aria in a clear, glass-bell voice. Nathanael was quite delighted; he was standing in the back row and could not quite make out Olimpia's features. So, quite unnoticed, he took out Coppola's glass and looked at the beautiful Olimpia. Ah! – then he noticed how she looked at him full of longing, how every note was clearly expressed in the loving look that ignited his inner being. The artificial embellishments seemed to Nathanael the heavenly exultation of a soul transfigured by love, and when finally, after the cadence, the long trill rang out loudly through the hall, he could no longer contain himself, he had to cry out loudly in pain and delight: “Olimpia!” – Everyone looked around at him, some laughed. The cathedral organist, however, pulled an even darker face than before and simply said: “Now, now!”

46 The concert was over, the ball began. To dance with her! – with her! that was now the goal of all Nathanael’s wishes. He himself did not know how it happened that, when the dance had already begun, he stood close to Olimpia, who had not yet been asked, and took her hand. Olimpia's hand was ice cold, he felt himself trembling with a terrible chill of death, he stared into Olimpia's eyes, which shone at him full of love and longing, and at that moment it was as if pulses began to beat in the cold hand and streams of life's blood began to glow. And Nathanael's inner being also glowed with love, he embraced the beautiful Olimpia and flew through the rows with her.

47 Heated up by the dance and the copious amounts of wine he had consumed, Nathanael had cast off all his usual shyness. He sat next to Olimpia, her hand in his, and spoke passionately of his love in words that no one understood, neither he nor Olimpia. But perhaps she did, for she looked him straight in the eye and sighed over and over again: "Ah - ah - ah!" - whereupon Nathanael said: "Oh, you glorious, heavenly woman! - you ray from the promised beyond of love," and more of the same. But Olimpia just kept sighing: "Ah, ah!"

48 Professor Spallanzani walked past the happy couple a few times and smiled at them with strange contentment. Nathanael suddenly felt as if things were getting noticeably dark at Professor Spallanzani's; he looked around and noticed, to his considerable horror, that the last two lights in the empty hall were about to go out. "Separation, separation," he screamed wildly and desperately, he kissed Olimpia's hand, he leaned towards her mouth, ice-cold lips met his glowing ones! - Just as when he touched Olimpia's cold hand, he felt an inner horror, the legend of the dead bride suddenly flashed through his mind; but Olimpia had pressed him tightly to her, and in the kiss her lips seemed to warm to life.

49 "Do you love me - do you love me, Olimpia? - Just this word! - Do you love me?" So whispered Nathanael, but Olimpia sighed as she stood up, only: "Ah - ah!" - "Yes, you, my lovely, glorious star of love," said Nathanael, "have risen for me and will shine, will transfigure my inner being forever!" - "Ah, ah!" replied Olimpia, striding forward. Nathanael followed her, and they stood in front of the professor. "You have had an extraordinarily lively conversation with my daughter," said the professor, smiling, "well, dear Mr. Nathanael, if you find it enjoyable to talk to the shy girl, then your visits shall be welcome." - With a whole bright, radiant sky in his chest, Nathanael left.

50 "Do me a favor, brother," said Siegmund one day, "do me a favor and tell me how you, clever fellow, were able to fall in love with that waxen face, that wooden doll over there?" Nathanael wanted to explode angrily, but quickly came to his senses and replied: "Tell me, Siegmund, how your gaze, which normally clearly perceives everything beautiful, could have missed the heavenly charm of Olimpia?" Siegmund noticed how things stood with his friend, skilfully relented and added: "It is strange that many of us judge Olimpia in much the same way. Olimpia has become quite uncanny to us, we didn't want to have anything to do with her, it seemed to us as if she was just acting like a living being." Nathanael simply said very seriously: "Olimpia may well be uncanny to you, you cold, prosaic people. Only the poetic mind unfolds the equally organized! But you have no understanding of all that, and all of it is wasted words.”

51 Professor Spallanzani seemed delighted with his daughter’s relationship with Nathanael; he gave him all sorts of unambiguous signs of his goodwill, and when Nathanael finally dared to hint at a relationship with Olimpia, the latter smiled with his whole face and said that he would give his daughter complete freedom of choice. – Encouraged by these words, Nathanael decided to implore Olimpia the very next day to say frankly in clear words what her lovely loving look had long since told him, that she wanted to be his forever.

52 Already on the stairs, in the hallway, he heard a strange noise; it seemed to be coming from Spallanzani’s study. – A stamping – a clatter – a pushing – banging against the door, interspersed with curses and imprecations. “Let go – let go – infamous – wicked man! – Is that why you risked your life and limb? – ha, ha, ha! – we didn’t wager like that – I, I made the eyes – I the clockwork – stupid devil with your clockwork – cursed dog of a simple watchmaker – get away with you – Satan – stop – puppet-maker – devilish beast! – stop – go – let go!” – It was Spallanzani’s and the horrible Coppelius’ voices that were buzzing together.

53 Nathanael rushed in, seized by nameless fear. The professor had grabbed a female figure by the shoulders, the Italian Coppola by the feet, and they were pulling and tugging them back and forth, fighting in full fury for possession. Nathanael recoiled in utter horror when he recognized the figure as Olimpia; Flaring up in wild anger, he wanted to snatch his beloved from the angry men, but at that moment Coppola, turning with enormous strength, wrested the figure from the professor's hands and dealt him a terrible blow with the figure itself, causing him to stagger backwards over the table on which there were phials, retorts, bottles and glass cylinders, and fall to the ground; all the equipment shattered into a thousand pieces.

54 Then Coppola threw the figure over his shoulder and ran quickly down the stairs with a horrible, piercing laughter. Nathanael stood frozen – he had seen only too clearly that Olimpia's deathly pale wax face had no eyes, but black sockets instead; she was a lifeless doll. Spallanzani rolled on the ground, shards of glass had cut his head, chest and arm, blood was pouring out like a fountain. But he gathered his strength. – “Follow him – follow him, why are you hesitating? – Coppelius – Coppelius, he stole my best machine from me – worked on it for twenty years – risked his life and limb – the gears – language – movement – ​​mine – the eyes – the eyes stolen from you. – Damned – accursed – follow him – get me Olimpia – there are the eyes!”

55 Now Nathanael saw a pair of bloody eyes lying on the floor staring at him, which Spallanzani grabbed with his uninjured hand and threw at him so that they hit his chest. – Then madness seized Nathanael with glowing claws and penetrated his inner being, tearing apart his senses and thoughts. “Whoa – woooo – woooo! – circle of fire – circle of fire! turn around, circle of fire – funny – funny! – wooden doll, woooo, lovely wooden doll, turn around” – with that he threw himself on the professor and squeezed his throat.

56 He would have strangled him, but the noise had attracted many people who forced their way in, tore the enraged Nathanael to his feet and saved the professor. Siegmund, strong as he was, could not control the madman; he kept screaming in a terrible voice: "Wooden doll, turn around," and struck around with clenched fists. Finally, the combined strength of several people managed to overpower him. His words were drowned out by a terrible, animalistic roar. Raging in this horrific frenzy, he was taken to the madhouse.

57 - Nathanael awoke as if from a heavy, terrible dream, he opened his eyes and felt an indescribable feeling of bliss flow through him. Klara had bent over him, and his mother and Lothar stood not far away. "Finally, finally, oh my dearest Nathanael - now you have recovered from a serious illness - now you are mine again!"
- Thus spoke Klara from the bottom of her heart and took Nathanael in her arms. But bright, glowing tears welled up from his eyes out of sheer sadness and delight, and he groaned deeply. "My Klara!" - Siegmund, who had faithfully stood by his friend in great need, came in. Nathanael held out his hand to him: "You faithful brother, you have not abandoned me after all."

58 Every trace of madness had disappeared, and Nathanael soon regained strength in the careful care of his mother, his lover, and his friends. In the meantime, happiness had returned to the house; for an old, penniless uncle, from whom no one had hoped for anything, had died and had left his mother, along with a not inconsiderable fortune, a small estate in a pleasant area not far from the city. They wanted to go there: the mother, Nathanael with his Clara, whom he now intended to marry, and Lothar.

59 It was time for the four happy people to go to the estate. At midday they walked through the streets of the town. They had bought a lot of things, the high town hall tower cast its gigantic shadow over the market. "Well!" said Clara, "let's climb up again and look into the distant mountains!" No sooner said than done! Both Nathanael and Clara climbed up, the mother went home with the maid, and Lothar, not inclined to climb the many steps, wanted to wait below. Then the two lovers stood arm in arm on the highest gallery of the tower and looked into the fragrant forests, behind which the blue mountains rose like a giant city.

60 "Look at the strange little grey bush that seems to be walking straight towards us," said Clara. Nathanael mechanically reached for his side pocket; he found Coppola's perspective, he looked sideways - Klara was standing in front of the glass! - Then his veins twitched convulsively - deathly pale he stared at Klara, but soon streams of fire glowed and sprayed through his rolling eyes, he roared horribly like a hunted animal; then he leapt high into the air, and laughing horribly in between, he screamed in a piercing tone: "Wooden doll, turn around - wooden doll, turn around" - and with tremendous strength he grabbed Klara and wanted to hurl her down, but Klara clung tightly to the railing in desperate fear of death.

61 Lothar heard the madman raging, he heard Klara's screams of fear, a terrible premonition ran through him, he ran upstairs, the door of the second flight of stairs was locked - Klara's cries of distress echoed louder. Mad with rage and fear, he pushed against the door, which finally burst open. – Klara's cries became fainter and fainter: "Help – save – save –" the voice died away in the air. "She's gone – murdered by the madman," Lothar screamed. The door to the gallery was also slammed shut. – Despair gave him enormous strength, he burst the door off its hinges. God in heaven – Klara, seized by the madman Nathanael, was floating in the air above the gallery – she was only still clutching the iron bars with one hand.

62 Quick as lightning, Lothar seized his sister, pulled her inside and at the same moment struck the madman in the face with his clenched fist, causing him to recoil and let go of his deadly prey. Lothar ran down, his unconscious sister in his arms. – She was saved.

63 Now Nathanael raced around the gallery and jumped high into the air and shouted: "Circle of fire, turn around - circle of fire, turn around." The people ran together at the wild shouting; among them towered the lawyer Coppelius, who had just come into the city and was walking straight to the market. They wanted to climb up to seize the madman, but Coppelius laughed, saying: "Ha, ha - just wait, he'll come down of his own accord," and looked up like the others.

64 Nathanael suddenly stood there as if frozen, he bent down, saw Coppelius, and with a piercing cry: "Ha! Sköne Oke - sköne Oke" he jumped over the railing. When Nathanael lay on the cobblestones with his head shattered, Coppelius had disappeared in the crowd.

65 Several years later, Clara was said to have been seen in a distant region, sitting hand in hand with a friendly man in front of the door of a beautiful country house, with two lively boys playing in front of her. It would be concluded from this that Clara still found the quiet domestic happiness that suited her cheerful, fun-loving spirit and that Nathanael, who was torn inside, could never have granted her.
"""


def generate_experiment_texts(experiment_config: dict[str, str]):
    """
    Generate prompts and experiment texts
    Args:
        experiment_config: settings to use in this experiment
    Return:
        Experiment prompts and version prompts
    """
    # Get experiment prompts
    prompts = {
        "Experiment": common_prompt_template,
    }

    # Get experiment texts
    experiment_texts = experiment_text.strip().split("\n\n")
    texts = {
        "Experiment": [
            ("Normal", experiment_texts),
        ],
    }

    return prompts, texts
